Web/LoLStats.Web/Areas/Administration/Controllers/AdministrationController.cs
namespace LoLStats.Web.Areas.Administration.Controllers
{
    using LoLStats.Common;
    using LoLStats.Web.Controllers;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
    [Area("Administration")]
    public class AdministrationController : BaseController
    {
    }
}

Web/LoLStats.Web/Areas/Administration/Controllers/DashboardController.cs
namespace LoLStats.Web.Areas.Administration.Controllers
{
    using LoLStats.Services.Data;
    using LoLStats.Web.ViewModels.Administration.Dashboard;

    using Microsoft.AspNetCore.Mvc;

    public class DashboardController : AdministrationController
    {
        private readonly ISettingsService settingsService;

        public DashboardController(ISettingsService settingsService)
        {
            this.settingsService = settingsService;
        }

        public IActionResult Index()
        {
            var viewModel = new IndexViewModel { SettingsCount = this.settingsService.GetCount(), };
            return this.View(viewModel);
        }
    }
}

Web/LoLStats.Web/Controllers/BaseController.cs
namespace LoLStats.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class BaseController : Controller
    {
    }
}

Web/LoLStats.Web/Controllers/ChampionsController.cs
namespace LoLStats.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using LoLStats.Services.Data;
    using LoLStats.Web.ViewModels;
    using LoLStats.Web.ViewModels.Champions;
    using Microsoft.AspNetCore.Mvc;

    public class ChampionsController : BaseController
    {
        private readonly IChampionsService championsService;

        public ChampionsController(IChampionsService championsService)
        {
            this.championsService = championsService;
        }

        public IActionResult All()
        {
            var viewModel = new ChampionsListViewModel
            {
                Champions = this.championsService.GetAll<ChampionInListViewModel>(),
            };

            return this.View(viewModel);
        }

        public async Task<IActionResult> ById(string id)
        {
            ChampionStatsViewModel viewModel = await this.championsService.GetById(id);

            return this.View(viewModel);
        }
    }
}

Web/LoLStats.Web/Controllers/GuidesController.cs
namespace LoLStats.Web.Controllers
{
    using LoLStats.Services.Data;
    using LoLStats.Web.ViewModels.Champions;
    using LoLStats.Web.ViewModels.Guides;
    using LoLStats.Web.ViewModels.SummonerSpells;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class GuidesController : BaseController
    {
        private readonly IChampionRolesService championRolesService;
        private readonly IChampionsService championsService;
        private readonly ISummonerSpellsService summonerSpellsService;

        public GuidesController(
            IChampionRolesService championRolesService,
            IChampionsService championsService,
            ISummonerSpellsService summonerSpellsService)
        {
            this.championRolesService = championRolesService;
            this.championsService = championsService;
            this.summonerSpellsService = summonerSpellsService;
        }

        public IActionResult All()
        {
            return this.View();
        }

        public IActionResult Create()
        {
            var viewModel = new GuideInputModel
            {
                Roles = this.championRolesService.GetAll(),
                AllChampions = this.championsService.GetAll<ChampionBasicViewModel>(),
                AllSummonerSpells = this.summonerSpellsService.GetAll<SummonerSpellViewModel>(),
            };

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create(GuideInputModel input)
        {
            return this.RedirectToAction(nameof(this.All));
        }
    }
}

Web/LoLStats.Web/Controllers/HomeController.cs
namespace LoLStats.Web.Controllers
{
    using System;
    using System.Collections.Concurrent;
    using System.Diagnostics;
    using System.Threading.Tasks;

    using LoLStats.Services;
    using LoLStats.Services.Data;
    using LoLStats.Web.ViewModels;
    using LoLStats.Web.ViewModels.Home;
    using Microsoft.AspNetCore.Mvc;

    public class HomeController : BaseController
    {
        private readonly IScraperService scraperService;
        private readonly IRiotSharpService riotSharpService;
        private readonly IDbService dbService;
        private readonly IHomeService homeService;

        public HomeController(IScraperService scraperService, IRiotSharpService riotSharpService, IDbService dbService, IHomeService homeService)
        {
            this.scraperService = scraperService;
            this.riotSharpService = riotSharpService;
            this.dbService = dbService;
            this.homeService = homeService;
        }

        public async Task<IActionResult> Index()
        {
            HomeViewModel homeViewModel = new HomeViewModel
            {
                BaseData = this.homeService.GetBaseGameCounts(),
                TopChampionsForRole = this.homeService.GetTopChampionsForEachRole(),
            };

            return this.View(homeViewModel);

            // return this.RedirectToAction(nameof(this.Privacy));
        }

        public async Task<IActionResult> Privacy()
        {
            // Testing
            // await this.dbService.AddBaseGameData();
            // await this.dbService.AddChampionStatisticsData();

            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(
                new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }
    }
}

Web/LoLStats.Web/Controllers/SearchController.cs
namespace LoLStats.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using LoLStats.Services.Data;
    using LoLStats.Web.ViewModels.Champions;
    using Microsoft.AspNetCore.Mvc;

    [ApiController]
    [Route("api/[controller]")]
    public class SearchController : BaseController
    {
        private readonly ISearchService searchService;

        public SearchController(ISearchService searchService)
        {
            this.searchService = searchService;
        }

        [HttpGet]
        public IActionResult ReturnChampions(string input)
        {
            var champions = this.searchService.ReturnChampions<ChampionBasicViewModel>(input);

            return this.View(champions);
        }
    }
}

Web/LoLStats.Web/Controllers/SettingsController.cs
namespace LoLStats.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using LoLStats.Data.Common.Repositories;
    using LoLStats.Data.Models;
    using LoLStats.Services.Data;
    using LoLStats.Web.ViewModels.Settings;

    using Microsoft.AspNetCore.Mvc;

    public class SettingsController : BaseController
    {
        private readonly ISettingsService settingsService;

        private readonly IDeletableEntityRepository<Setting> repository;

        public SettingsController(ISettingsService settingsService, IDeletableEntityRepository<Setting> repository)
        {
            this.settingsService = settingsService;
            this.repository = repository;
        }

        public IActionResult Index()
        {
            var settings = this.settingsService.GetAll<SettingViewModel>();
            var model = new SettingsListViewModel { Settings = settings };
            return this.View(model);
        }

        public async Task<IActionResult> InsertSetting()
        {
            var random = new Random();
            var setting = new Setting { Name = $"Name_{random.Next()}", Value = $"Value_{random.Next()}" };

            await this.repository.AddAsync(setting);
            await this.repository.SaveChangesAsync();

            return this.RedirectToAction(nameof(this.Index));
        }
    }
}

Web/LoLStats.Web/Areas/Administration/Views/Dashboard/Index.cshtml
@model LoLStats.Web.ViewModels.Administration.Dashboard.IndexViewModel
@{
    this.ViewData["Title"] = "Admin dashboard";
}

<h1>@this.ViewData["Title"]</h1>
Settings: @this.Model.SettingsCount

Web/LoLStats.Web/Views/Champions/All.cshtml
@model LoLStats.Web.ViewModels.Champions.ChampionsListViewModel
@{
    this.ViewData["Title"] = "All Champions";
}

<div class="container-fluid bg-gray-200">

    <div class="container-fluid row col-md-6">
        <h1 class="h1 font-weight-bolder">All Champions:</h1>
    </div>
    <div class="row col-lg-8 container-fluid bg-gray-400 table-bordered">
        @foreach (var champion in this.Model.Champions)
        {
        <div class="img-with-text col-md-1">
            <a asp-controller="Champions" asp-action="ById" asp-route-id="@champion.Id"><img src="@champion.ImageUrl" alt="champion-icon" width="80" height="80" class="img-thumbnail img-fluid"></a>
            <h6 class="h6 text-primary font-weight-bold">@champion.Name</h6>
        </div>
        }
    </div>

</div>

Web/LoLStats.Web/Views/Champions/ById.cshtml
@model LoLStats.Web.ViewModels.Champions.ChampionStatsViewModel
@{
    this.ViewData["Title"] = "ChampionPage";
}

<style>
    .red-tooltip + .tooltip > .tooltip-inner {
        background-color: #f00;
    }
</style>

<div class="container">
    <div class="card shadow mb-4">

        @*<div class="col-md-2">
            <img src="@Model.ChampionRole.ImagePath" alt="role-icon" class="img-fluid">
        </div>*@

        <a href="#" data-toggle="tooltip" data-placement="bottom"
           title="" data-original-title="Tooltip on bottom"
           class="red-tooltip">Tooltip on bottom</a>

        <!-- HTML to write -->
        <a href="#" data-toggle="tooltip" title="Some tooltip text!">Hover over me</a>

        <!-- Generated markup by the plugin -->
        <div class="tooltip bs-tooltip-top" role="tooltip">
            <div class="arrow"></div>
            <div class="tooltip-inner">
                Some tooltip text!
            </div>
        </div>

        <div class="container row d-flex justify-content-center">
            <div class="col-md-2">
                <img src="@Model.ImageUrl" alt="champion-icon" width="100" height="100" class="img-fluid fa-pull-left rounded">
            </div>

            <div class="col-md-10 text-left">
                <h1 class="h1"><strong class="text-primary">@Model.Name</strong> build for <br><strong class="h1 text-danger">@Model.ChampionRole.Role</strong></h1>
            </div>

            @*<div class="col-md-6 offset-5">
            <h1 class="h1"><strong class="text-primary">@Model.Name</strong> build for <p class="text-danger">@Model.ChampionRole.Role</p></h1>
        </div>*@
        </div>

        <div class="card-body col-md-12">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Recommmended Skill Priority</th>
                            <th>Win Rate</th>
                            <th>Total Matches</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class"container">

                                @foreach (var ability in Model.BestAbilities.First().Abilities)
                                {
                                    <!--<div id="parent">-->
                                    <!-- This is the main container, to mouse over -->
                                    <!--<img src="@ability.ImageUrl" width="50" height="50" alt="ability-icon">
            <div class="bg-dark col-md-4" id="popup" style="display: none">@ability.Description</div>
        </div>-->
                                    @if (ability.IsFirst)
                                    {
                                        <i class="fas fa-arrow-right"></i>
                                    }
                                    <img src="@ability.ImageUrl" width="50" height="50" alt="ability-icon" data-toggle="tooltip" data-html="true" title="@ability.Name" id=@ability .>
                                    @*<img src="@ability.ImageUrl" width="50" height="50" alt="ability-icon">
            <div id="popup" style="display: none">@ability.Description</div>*@
                                }
                            </td>
                            <td>@Model.BestAbilities.First().WinRate</td>
                            <td>@Model.BestAbilities.First().TotalMatches</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Recommmended Summoner Spells</th>
                            <th>Win Rate</th>
                            <th>Total Matches</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class"container">
                                @foreach (var summonerSpell in Model.BestSummonerSpells.First().SummonerSpells)
                                {
                                    <img src="@summonerSpell.ImageUrl" width="50" height="50" alt="summonerspell-icon" class="img-fluid">
                                }
                            </td>
                            <td>@Model.BestSummonerSpells.First().WinRate</td>
                            <td>@Model.BestSummonerSpells.First().TotalMatches</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Recommmended Starting Items</th>
                            <th>Win Rate</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class"container">
                                @foreach (var item in Model.BestStartingItems.First().Items)
                                {
                                    <img src="@item.ImageUrl" width="50" height="50" alt="item-icon" class="img-fluid">
                                }
                            </td>
                            <td>@Model.BestStartingItems.First().WinRate</td>
                        </tr>
                    </tbody>
                </table>
            </div>


            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Recommmended Final Build</th>
                            <th>Win Rate</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class"container">
                                @foreach (var item in Model.BestItems.First().Items)
                                {
                                    <img src="@item.ImageUrl" width="50" height="50" alt="item-icon" class="img-fluid">
                                }
                            </td>
                            <td>@Model.BestItems.First().WinRate</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Recommmended Runes</th>
                            <th>Win Rate</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class"container">

                                <div class="container col-sm-4 float-left border-right">

                                    <div class="col-md-12 d-flex justify-content-center">
                                        @foreach (var rune in this.Model.PrimaryRunesKeystoneRow)
                                        {
                                            <img src="@rune.ImageUrl" width="50" height="50" alt="rune-icon" class="img-fluid">
                                        }
                                    </div>

                                    <div class="col-md-12 d-flex justify-content-center">
                                        @foreach (var rune in this.Model.PrimaryRunesSecondRow)
                                        {
                                            <img src="@rune.ImageUrl" width="50" height="50" alt="rune-icon" class="img-fluid">
                                        }
                                    </div>

                                    <div class="col-md-12 d-flex justify-content-center">
                                        @foreach (var rune in this.Model.PrimaryRunesThirdRow)
                                        {
                                            <img src="@rune.ImageUrl" width="50" height="50" alt="rune-icon" class="img-fluid">
                                        }
                                    </div>

                                    <div class="col-md-12 d-flex justify-content-center">
                                        @foreach (var rune in this.Model.PrimaryRunesFourthRow)
                                        {
                                            <img src="@rune.ImageUrl" width="50" height="50" alt="rune-icon" class="img-fluid">
                                        }
                                    </div>

                                </div>

                                <div class="container col-sm-4 float-left border-left border-right">

                                    <div class="col-md-12 d-flex justify-content-center">
                                        @foreach (var rune in this.Model.SecondaryRunesSecondRow)
                                        {
                                            <img src="@rune.ImageUrl" width="50" height="50" alt="rune-icon" class="img-fluid">
                                        }
                                    </div>

                                    <div class="col-md-12 d-flex justify-content-center">
                                        @foreach (var rune in this.Model.SecondaryRunesThirdRow)
                                        {
                                            <img src="@rune.ImageUrl" width="50" height="50" alt="rune-icon" class="img-fluid">
                                        }
                                    </div>

                                    <div class="col-md-12 d-flex justify-content-center">
                                        @foreach (var rune in this.Model.SecondaryRunesFourthRow)
                                        {
                                            <img src="@rune.ImageUrl" width="50" height="50" alt="rune-icon" class="img-fluid">
                                        }
                                    </div>

                                </div>

                                <div class="container col-sm-4 float-left border-left">
                                    <div class="col-md-12 d-flex justify-content-center">
                                        @foreach (var statRune in this.Model.StatRunesFirstRow)
                                        {
                                            <img src="@statRune.ImagePath" alt="statrune-icon" class="img-fluid">
                                        }
                                    </div>
                                    <div class="col-md-12 d-flex justify-content-center">
                                        @foreach (var statRune in this.Model.StatRunesSecondRow)
                                        {
                                            <img src="@statRune.ImagePath" alt="statrune-icon" class="img-fluid">
                                        }
                                    </div>
                                    <div class="col-md-12 d-flex justify-content-center">
                                        @foreach (var statRune in this.Model.StatRunesThirdRow)
                                        {
                                            <img src="@statRune.ImagePath" alt="statrune-icon" class="img-fluid">
                                        }
                                    </div>
                                </div>

                            </td>
                            <td>@Model.BestRunes.First().WinRate</td>
                        </tr>
                    </tbody>
                </table>
            </div>

        </div>

    </div>

</div>

<script>
    $(document).ready(function () {
        $("a").tooltip();
    });
</script>

Web/LoLStats.Web/Views/Guides/All.cshtml
@{
    this.ViewData["Title"] = "All Builds";
}

<h1 class="h1">To be implemented...</h1>

Web/LoLStats.Web/Views/Guides/Create.cshtml
@model LoLStats.Web.ViewModels.Guides.GuideInputModel

@{
    this.ViewData["Title"] = "Create Build";
}

<style>
    img-fluid {
        display: inline-block;
        border-radius: 60px;
        box-shadow: 0px 0px 2px #888;
        padding: 0.5em 0.6em;
    }
</style>

<form method="post" class="col-md-6 offset-md-3"
      enctype="multipart/form-data">
    <h1 class="h1 text-primary">@this.ViewData["Title"]</h1>
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="GuideTitle">Guide Title</label>
        <input asp-for="GuideTitle" class="form-control" />
        <span asp-validation-for="GuideTitle" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="ChampionRole">Role</label>
        <div>
            @foreach (var role in Model.Roles)
            {
                <img src="@role.ImagePath" alt="@role.Name" data-content="@role.Name" id="@role.Name" class="img-fluid btn rounded">
            }
        </div>
        <input asp-for="GuideTitle" class="form-control" />
        <span asp-validation-for="ChampionRole" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="ChampionName">Champion</label>
        <div class="container bg-gradient-secondary">
            @foreach (var champion in Model.AllChampions)
            {
                <img src="@champion.ImageUrl" alt="@champion.Name" data-content="@champion.Id" id="@champion.Id" class="img-fluid btn col-md-1">
            }
        </div>
        <input asp-for="ChampionName" type="hidden" class="form-control" />
        <span asp-validation-for="ChampionName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="SummonerSpellA">Summoner Spells</label>
        <div>
            @foreach (var spell in Model.AllSummonerSpells)
            {
                <img src="@spell.ImageUrl" alt="@spell.Name" data-content="@spell.Key" id="@spell.Key" class="img-fluid btn rounded">
            }
        </div>
        <input asp-for="SummonerSpellA" class="form-control" />
        <input asp-for="SummonerSpellB" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="RunesNotes">Runes</label>
        <div>
            @foreach (var spell in Model.AllSummonerSpells)
            {
                <img src="@spell.ImageUrl" alt="@spell.Name" data-content="@spell.Key" id="@spell.Key" class="img-fluid btn rounded">
            }
        </div>
        <input asp-for="SummonerSpellA" class="form-control" />
        <input asp-for="SummonerSpellB" class="form-control" />
    </div>

    <input type="submit" class="btn btn-primary" />
</form>

@section Scripts {
    <script>
        $("img[data-content]").each(function (el) {
            $(this).click(function (e) {
                e.preventDefault();
                var value = $(this).attr("data-content");
                var input = $(this).parent().parent().children("input");
                var inputIndex = 0;

                var isSummonerSpell = value.includes("Summoner");

                if (isSummonerSpell) {
                    var selectFirstField = input[0].value == "" && input[1].value != value || input[0].value === value;

                    if (selectFirstField) {
                        inputIndex = 0;
                    }
                    else {
                        inputIndex = 1;
                    }
                }

                var isSame = input[inputIndex].value === value;

                if (input[inputIndex].value !== value && input[inputIndex].value !== "" || input[inputIndex].value === value) {
                    var selectedImage = $("#" + input[inputIndex].value);
                    selectedImage.css('border-color', 'transparent')
                    input[inputIndex].value = "";
                }
                if (!isSame) {
                    input[inputIndex].value = value;
                    $(this).css('border-color', 'lime');
                }
            })
        });
    </script>
    <script type="text/javascript">
        function Login() {

            var Login = {};
            Login.username = $("#txtUserName").val();

            $.ajax({
                url: '/api/Login/',
                method: 'POST',
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                data: Login,
                success: function (data) {
                    alert("Saved successfully");
                },
                fail: function (jqXHR, textStatus) {
                    alert("Request failed: " + textStatus);
                }
            })
        }
    </script>
}

Web/LoLStats.Web/Views/Guides/_ChampionsPartial.cshtml
<div class="alert alert-dark">

</div>

Web/LoLStats.Web/Views/Shared/_Layout.cshtml
@using LoLStats.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/js/sb-admin-2.min.js" rel="stylesheet" asp-append-version="true" />
    <link href="~/lib/fontawesome/css/all.css" rel="stylesheet" asp-append-version="true" />
    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Champions" asp-action="All">Champions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Guides" asp-action="All">Guides</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container-fluid">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>

    <!-- Footer -->
    <footer class="blockquote-footer bg-white">
        <div class="container clear-top col-md-auto fixed-bottom">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            <div class="copyright text-break">
                LoLStats isn’t endorsed by Riot Games and doesn’t reflect the views or opinions of Riot Games or anyone officially involved in producing or managing League of Legends. League of Legends and Riot Games are trademarks or registered trademarks of Riot Games, Inc. League of Legends © Riot Games, Inc.
            </div>
        </div>
    </footer>
    <!-- End of Footer -->
    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="js/demo/chart-area-demo.js"></script>
    <script src="js/demo/chart-pie-demo.js"></script>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>